services:
  java-finflow-notification-service:
    build: .
    ports: ["9004:9004"]
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP-ID: notification-service-group
    networks:
      - finflow-shared
    restart: on-failure:5

networks:
  finflow-shared:
    external: true
    name: finflow-java-shared
