version: '3.8'
services:
  notification-app:
    build: .
    container_name: java-notification-app
    ports:
      - "9004:9004"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:19092